# Generated by Django 4.2.3 on 2023-07-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailinglog',
            old_name='client',
            new_name='mailing',
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='mailing_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рассылки'),
        ),
    ]
